#!/usr/bin/env node

const chalk = require('chalk');
const program = require('commander');

const { date_calc } = require('./date_calc.js')
const log = console.log
const printResult = (date1, date2, totalDays) => log(chalk.green(`${date1} - ${date2} : ${totalDays} day(s)`))

program
  .version('0.0.1')
  .usage("date1<Format: DD/MM/YYYY> date2<Format: DD/MM/YYYY>\ne.g. date_calc 02/06/1983 05/06/1983")
  .parse(process.argv);

if( program.args.length >= 2 ) {
  const result = date_calc(program.args[0], program.args[1]);
  if (result >= 0) {
    printResult(program.args[0], program.args[1], result);
    process.exit();
  }
} 

program.help();

